/*
 * Proteus Ecosystem — Native C-FFI Header
 * Autogenerated & Bespoke header for C, C++, Objective-C, Swift & Kotlin/NDK.
 * Part of the Proteus Portable Business Operating System (BOS).
 */

#ifndef PROTEUS_CORE_H
#define PROTEUS_CORE_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Returns the static semantic version string of Proteus Core (e.g. "0.1.0-native").
 * The returned pointer is statically allocated and MUST NOT be freed.
 */
const char* proteus_core_version(void);

/**
 * Parses a database connection URL (sqlite://, postgres://, mysql://)
 * and returns a JSON string representing the ConnectionConfig.
 * Returns NULL on critical allocation error.
 * Caller MUST free the returned string using `proteus_free_string()`.
 */
char* proteus_parse_connection_url(const char* url_ptr);

/**
 * Evaluates a business rule (JSON) against an arbitrary JSON data context.
 * Writes the outcome JSON into out_buf (up to max_len bytes).
 * 
 * Returns:
 *   0  : Success
 *  -1  : Invalid pointer or max_len == 0
 *  -2  : JSON parse error
 *  -3  : Buffer too small
 */
int32_t proteus_eval_rule(
    const char* rule_json_ptr,
    const char* ctx_json_ptr,
    char* out_buf,
    size_t max_len
);

/**
 * Decodes GS1-128 barcode Application Identifiers into a JSON array of parsed elements.
 * Writes the decoded JSON into out_buf (up to max_len bytes).
 *
 * Returns:
 *   0  : Success
 *  -1  : Invalid pointer or max_len == 0
 *  -2  : Serialization error
 *  -3  : Buffer too small
 */
int32_t proteus_parse_gs1(
    const char* barcode_ptr,
    char* out_buf,
    size_t max_len
);

/**
 * Frees a heap-allocated C string returned by any Proteus FFI function.
 * Safe to pass NULL.
 */
void proteus_free_string(char* ptr);

#ifdef __cplusplus
}
#endif

#endif /* PROTEUS_CORE_H */
