//! Domain models and error types for multi-store logistics and automated stock level arbitrage.
//! Designed from first principles for zero-rewrite database federation.

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Operational lifecycle status of an inter-store inventory transfer order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TransferStatus {
    Draft,
    Approved,
    InTransit,
    Completed,
    Cancelled,
}

impl TransferStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Draft => "DRAFT",
            Self::Approved => "APPROVED",
            Self::InTransit => "IN_TRANSIT",
            Self::Completed => "COMPLETED",
            Self::Cancelled => "CANCELLED",
        }
    }

    pub fn from_str(s: &str) -> Self {
        match s {
            "DRAFT" => Self::Draft,
            "APPROVED" => Self::Approved,
            "IN_TRANSIT" => Self::InTransit,
            "COMPLETED" => Self::Completed,
            "CANCELLED" => Self::Cancelled,
            _ => Self::Draft,
        }
    }
}

/// Priority tier of an automated or manual transfer order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum TransferPriority {
    Low,
    Normal,
    High,
    Urgent,
}

impl TransferPriority {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Low => "LOW",
            Self::Normal => "NORMAL",
            Self::High => "HIGH",
            Self::Urgent => "URGENT",
        }
    }

    pub fn from_str(s: &str) -> Self {
        match s {
            "LOW" => Self::Low,
            "NORMAL" => Self::Normal,
            "HIGH" => Self::High,
            "URGENT" => Self::Urgent,
            _ => Self::Normal,
        }
    }
}

/// Current stock position for a specific SKU inside an autonomous store node.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StoreStockLevel {
    pub store_id: String,
    pub sku: String,
    pub barcode: Option<String>,
    pub quantity_on_hand: f64,
    pub quantity_reserved: f64,
    pub min_reorder_point: f64,
    pub max_target_capacity: f64,
    pub unit_cost: f64,
    pub last_updated_at: String,
}

impl StoreStockLevel {
    /// Available unallocated stock ready for dispatch or sales.
    pub fn available_quantity(&self) -> f64 {
        (self.quantity_on_hand - self.quantity_reserved).max(0.0)
    }

    /// Quantity deficit below minimum reorder threshold.
    pub fn deficit_quantity(&self) -> f64 {
        let avail = self.available_quantity();
        if avail < self.min_reorder_point {
            self.min_reorder_point - avail
        } else {
            0.0
        }
    }

    /// Transferable surplus available above reorder safety margin.
    pub fn surplus_quantity(&self) -> f64 {
        let avail = self.available_quantity();
        if avail > self.min_reorder_point {
            avail - self.min_reorder_point
        } else {
            0.0
        }
    }
}

/// Automated intra-enterprise stock balancing recommendation generated by the arbitrage engine.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StockTransferRecommendation {
    pub recommendation_id: String,
    pub sku: String,
    pub deficit_store_id: String,
    pub deficit_quantity: f64,
    pub surplus_store_id: String,
    pub surplus_available: f64,
    pub recommended_transfer_qty: f64,
    pub arbitrage_reason: String,
    pub priority: TransferPriority,
}

/// Official transfer order dispatched between stores.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TransferOrder {
    pub order_id: String,
    pub from_store_id: String,
    pub to_store_id: String,
    pub sku: String,
    pub requested_qty: f64,
    pub status: TransferStatus,
    pub priority: TransferPriority,
    pub reason: String,
    pub created_at: String,
    pub updated_at: String,
}

/// Error domain for multi-store logistics and arbitrage.
#[derive(Debug, Error)]
pub enum LogisticsError {
    #[error("Database error: {0}")]
    Sql(#[from] rusqlite::Error),
    #[error("Serialization error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("Insufficient surplus stock: available {available}, requested {requested}")]
    InsufficientStock { available: f64, requested: f64 },
    #[error("Invalid order state transition from {from:?} to {to:?}")]
    InvalidStateTransition {
        from: TransferStatus,
        to: TransferStatus,
    },
    #[error("Order not found: {0}")]
    OrderNotFound(String),
}
